%YAML:1.0

# /////////////////////////
# // IONLAB ISAE-SUPAERO //
# // TELLO SLAM PROJECT  //
# /////////////////////////

# camera_model: {"Pinhole", "Brown-Conrady"}

# Tello camera ////////////////////////////////////////////////////////////////
# Camera Model
Tello.camera_model: "Brown-Conrady"

# camera matrix
# [ fx, 0, cx, 0, fy, cy, 0, 0, 1 ]
Tello.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 604.148, 0, 307.323,
           0, 604.148, 235.238,
           0, 0, 1 ]

# distortion coefficients
# [ k1, k2, p1, p2 [, k3 [, k4, k5, k6 [, s1, s2, s3, s4 [,τx ,τy]]]] ]
Tello.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -0.211958, 0.756105, 0,  0,  -1.01531 ]
    
# USB camera /////////////////////////////////////////////////////////////////
# camera model
USB.camera_model: "Brown-Conrady"

# camera matrix
# [ fx, 0, cx, 0, fy, cy, 0, 0, 1 ]
USB.K: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [ 1071.73, 0, 974.235, 
         0, 1067.18, 468.747, 
         0, 0, 1 ]

# distortion coefficients
# [ k1, k2, p1, p2 [, k3 [, k4, k5, k6 [, s1, s2, s3, s4 [,τx ,τy]]]] ]
USB.D: !!opencv-matrix
   rows: 1
   cols: 5
   dt: d
   data: [ -0.00812691, -0.0626833, -0.00270231, -0.00430813, 0.0268622 ]
